### ISSUE TITLE
Fix wrong method name

### ISSUE THREAD

**Issue by ma0dubois** [nenes25/prestashop_console#14]
Hi  :)

https://github.com/nenes25/prestashop_console/blob/27715a25067b1c3b7ef375c74698c542157e96ef/src/Hhennes/PrestashopConsole/Command/Module/ResetCommand.php#L82

**Fix:**

```php
$output->writeln("<error>Module: '$moduleName' $e->getMessage()</error>"); 
```

**Comment by nenes25** [comment]
Thanks for the report, i'll correct this quickly ;)
