### ISSUE TITLE
Error when try to start by prestashopConsole command

### ISSUE THREAD

**Issue by Evil1991** [nenes25/prestashop_console#142]
root@vm-02ac6d05:/var/www/testforplugins2/www# prestashopConsole
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The "phar:///var/www/testforplugins2/www/prestashopConsole/src/Hhennes/PrestashopConsole/Command" directory does not exist.' in /var/www/testforplugins2/www/vendor/symfony/symfony/src/Symfony/Component/Finder/Finder.php:547
Stack trace:
#0 phar:///usr/local/bin/prestashopConsole/src/Hhennes/PrestashopConsole/PrestashopConsoleApplication.php(66): Symfony\Component\Finder\Finder->in('phar:///var/www...')
#1 phar:///usr/local/bin/prestashopConsole/bin/phar/consolePhar.php(34): Hhennes\PrestashopConsole\PrestashopConsoleApplication->getDeclaredCommands()
#2 /usr/local/bin/prestashopConsole(10): require('phar:///usr/loc...')
#3 {main}
  thrown in /var/www/testforplugins2/www/vendor/symfony/symfony/src/Symfony/Component/Finder/Finder.php on line 547

**Comment by nenes25** [comment]
Hi,
This error seems to be related to this feature of issue #47 
Is /var/www/testforplugins2/www the root of your project or of your global web directory ?
