### ISSUE TITLE
Customer creation fails because of "Validate::isCustomerName()" not available.

### ISSUE THREAD

**Issue by SebSept** [nenes25/prestashop_console#191]
#### Describe the bug
Customer creation fails

### PrestashopConsole Version
2.0.0

### Prestashop Version
1.7.5.1

### Php Version
7.2

### Additional context
```sh
 [Exec] running php72 $(which prestashopConsole) customer:create --email "xxx@yahoo.fr" --password "xxx" --firstname Sebastien --lastname Doe
 ```
PHP Fatal error:  Uncaught Error: Call to undefined method Validate::isCustomerName() in phar:///home/http/github/prestashop_console/bin/prestashopConsole.phar/src/PrestashopConsole/Command/Customer/CreateCommand.php:85

**Comment by nenes25** [comment]
Nice catch @SebSept  , this function was only added in 2019 and in branch 1.7.6 !

**Comment by nenes25** [comment]
This is fixed in the branch ;), but this version will not be release soon as i've other thing in progress in the old branch :)

**Comment by SebSept** [comment]
nice, as I use prestashopConsole only on my computer, I'll use this version :)
Thanks 👍🏼
