### ISSUE TITLE
Should allow renaming

### ISSUE THREAD

**Issue by dvershinin** [nenes25/prestashop_console#47]
I've downloaded  the `.phar` to run with the **Thirtybees** Prestashop fork, then renamed it simply `prestashopConsole`.

This gives lots of HTML emitted into the console, with 500 error.

The exception log then has:

```
*ERROR* 	2019/09/22 - 00:21:14: The "phar:///var/www/html/prestashopConsole.phar/src/Hhennes/PrestashopConsole/Command" directory does not exist. at line 547 in file phar:///prestashopConsole/src/vendor/symfony/finder/Finder.php
```
Note that it is still trying to lookup things with prestashopConsole**.phar** even when the file has no extension.

Same situation if it is renamed to anything else, like `prestashop-console.phar`.

P.S. My personal preference is that it doesn't have `.phar` extension and following conventions of other E-Commerce frameworks/site, it should be kept simple, like `magento`, `wp` (some other CLI tools for Magento 2 and Wordpress). So simply `prestashop`.

P.P.S. It has a similar issue when simply placed in `/usr/local/bin/prestashopConsole.phar`, without renaming:

```
*ERROR*         2019/09/22 - 00:55:59: The "phar:///var/www/html/prestashopConsole.phar/src/Hhennes/PrestashopConsole/Command" directory does not exist. at line 547 in file phar:///usr/local/bin/prestashopConsole.phar/src/vendor/symfony/finder/Finder.php
```

**Comment by nenes25** [comment]
Hi,
Thanks for your feedback.
Let's first fix the rename of the phar file.
I'll after check how could this file be placed in /usr/local/bin

I'll see asap,
Regards,

**Comment by nenes25** [comment]
The change is done
