### ISSUE TITLE
Allow to install ps 1.7 versions with command install:install

### ISSUE THREAD

**Issue by nenes25** [nenes25/prestashop_console#59]
The install command only allow to install ps 1.6.1 versions.
Add 1.7 version support

**Comment by m3uusi** [comment]
At the moment, the installation of prestashop 1.6 doesn't work.
Use this issue to correct this also.

-> Dowload link must be https (http redirects to https I suppose but http returns no conten)
-> In my environment, the exec function does not work in the current directory. system function seems to work.

**Comment by nenes25** [comment]
As composer installation is now availaible this fuctionnality won't be necessary
